# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20170211_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
