# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_album_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('thumbnail', models.FileField(upload_to=music.models.get_upload_file_name)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
