# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20170217_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruzamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_01', models.CharField(max_length=10)),
                ('gene_02', models.CharField(max_length=10)),
                ('gene_03', models.CharField(max_length=10)),
                ('gene_04', models.CharField(max_length=10)),
            ],
        ),
    ]
