# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_cruzamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruzamentos',
            name='gene_01',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cruzamentos',
            name='gene_02',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cruzamentos',
            name='gene_03',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cruzamentos',
            name='gene_04',
            field=models.CharField(max_length=40),
        ),
    ]
